// Colección curada de productos absurdos que, contra todo pronóstico, triunfaron en ventas.
const PRODUCTOS_BASE = [
  {
    id: "pet-rock",
    nombre: "Pet Rock (la piedra mascota)",
    descripcion: "Una piedra normal y corriente, metida en una caja con agujeros de aire como si fuera a asfixiarse, vendida como 'la mascota perfecta': no come, no ladra, no se muere.",
    categoria: "Mascotas",
    emoji: "🪨",
    año: 1975,
    precioAprox: "4 $",
    ventas: "1,5 millones en 6 meses",
    chorrada: 5,
    porQueTriunfo: "Vendía una broma tan bien contada que se convirtió en el regalo de moda de la Navidad de 1975."
  },
  {
    id: "chia-pet",
    nombre: "Chia Pet",
    descripcion: "Figuritas de barro con forma de animal a las que le crece 'pelo' de semillas de chía. Ch-ch-ch-Chia.",
    categoria: "Hogar",
    emoji: "🌱",
    año: 1977,
    precioAprox: "20 $",
    ventas: "Más de 500 millones de dólares acumulados",
    chorrada: 4,
    porQueTriunfo: "Un jingle pegadizo y el morbo de ver 'crecer pelo' a una maceta lo convirtieron en clásico navideño."
  },
  {
    id: "snuggie",
    nombre: "Snuggie",
    descripcion: "Una manta... con mangas. Básicamente una bata puesta del revés vendida como revolución del sofá.",
    categoria: "Hogar",
    emoji: "🛋️",
    año: 2008,
    precioAprox: "20 $",
    ventas: "Más de 30 millones de unidades",
    chorrada: 4,
    porQueTriunfo: "Un anuncio de TV tan surrealista que se volvió meme, y el meme vendió mantas por millones."
  },
  {
    id: "pepinillo-cantor",
    nombre: "Pepinillo cantor (Yodelling Pickle)",
    descripcion: "Un pepinillo de plástico que, al apretarlo, suelta un yodel a pleno pulmón. Sin ninguna utilidad más allá de asustar a tu abuela.",
    categoria: "Juguetes",
    emoji: "🥒",
    año: 1990,
    precioAprox: "10 $",
    ventas: "Cientos de miles, aún se vende hoy",
    chorrada: 5,
    porQueTriunfo: "Es tan absurdo que se ha convertido en regalo de broma de culto durante más de 30 años."
  },
  {
    id: "slap-bracelet",
    nombre: "Slap Bracelets (pulseras chasca)",
    descripcion: "Una tira de metal forrada que, al golpearla contra tu muñeca, se enrolla sola formando una pulsera.",
    categoria: "Moda",
    emoji: "⚡",
    año: 1990,
    precioAprox: "5 $",
    ventas: "Millones, prohibidas en varios colegios por 'peligrosas'",
    chorrada: 3,
    porQueTriunfo: "El factor 'chas' es adictivo y las prohibiciones escolares le dieron publicidad gratis."
  },
  {
    id: "fidget-spinner",
    nombre: "Fidget Spinner",
    descripcion: "Un trozo de plástico o metal con rodamientos que gira sobre tu dedo. No hace nada más. Absolutamente nada.",
    categoria: "Juguetes",
    emoji: "🌀",
    año: 2017,
    precioAprox: "5 $",
    ventas: "Cientos de millones en un solo año",
    chorrada: 4,
    porQueTriunfo: "Se viralizó como 'anti-estrés' justo cuando TikTok e Instagram necesitaban contenido girador."
  },
  {
    id: "cubica-huevos",
    nombre: "Cubicador de huevos",
    descripcion: "Un tubo donde metes un huevo cocido pelado y, tras un rato de presión, sale... un huevo cuadrado. Para sándwiches 'más eficientes'.",
    categoria: "Cocina",
    emoji: "🧊",
    año: 2000,
    precioAprox: "12 $",
    ventas: "Producto de culto en tiendas de regalos",
    chorrada: 5,
    porQueTriunfo: "Resuelve un problema que nadie tenía, pero resulta tan hipnótico que la gente lo compra igual."
  },
  {
    id: "pelador-platano",
    nombre: "Cortador de plátano (Banana Slicer)",
    descripcion: "Un utensilio de plástico con forma de plátano que corta rodajas... de plátano. Como si un cuchillo no existiera.",
    categoria: "Cocina",
    emoji: "🍌",
    año: 2008,
    precioAprox: "5 $",
    ventas: "Viral en Amazon por sus reseñas absurdas",
    chorrada: 5,
    porQueTriunfo: "Sus reseñas de Amazon, escritas como sketches de comedia, lo convirtieron en fenómeno viral."
  },
  {
    id: "silla-invisible",
    nombre: "Nada Chair (la silla invisible)",
    descripcion: "Literalmente un cinturón con dos correas para las piernas que simula que te sientas en una silla... que no existe.",
    categoria: "Hogar",
    emoji: "🪑",
    año: 2019,
    precioAprox: "60 $",
    ventas: "Financiado x20 en crowdfunding",
    chorrada: 5,
    porQueTriunfo: "El concepto es tan ridículo y minimalista que despertó curiosidad y humor a partes iguales."
  },
  {
    id: "gafas-abrebotellas",
    nombre: "Gafas de sol abrebotellas",
    descripcion: "Gafas de sol normales, salvo por una patilla que incorpora un abrebotellas. Fiesta y estilo en un solo objeto.",
    categoria: "Moda",
    emoji: "🕶️",
    año: 2010,
    precioAprox: "15 $",
    ventas: "Best-seller en tiendas de fiesta y playa",
    chorrada: 4,
    porQueTriunfo: "Combina dos necesidades del verano (ver bien y abrir cervezas) en un chiste que además funciona."
  },
  {
    id: "poo-pourri",
    nombre: "Poo-Pourri",
    descripcion: "Un spray que se echa en el váter ANTES de hacer tus necesidades para que no huela. Sí, antes.",
    categoria: "Hogar",
    emoji: "🚽",
    año: 2007,
    precioAprox: "10 $",
    ventas: "Más de 45 millones de dólares en ventas anuales",
    chorrada: 3,
    porQueTriunfo: "Un anuncio viral buenísimo y sin tabúes hizo que millones hablaran (¡y compraran!) sobre caca."
  },
  {
    id: "squatty-potty",
    nombre: "Squatty Potty",
    descripcion: "Un taburete curvo que se coloca bajo el váter para poner los pies en una postura 'más natural' al hacer caca.",
    categoria: "Salud",
    emoji: "🦄",
    año: 2011,
    precioAprox: "25 $",
    ventas: "Más de 1 millón de unidades tras su anuncio viral",
    chorrada: 4,
    porQueTriunfo: "Un anuncio con un unicornio cagando helado en Shark Tank lo volvió inolvidable e imparable."
  },
  {
    id: "bop-it",
    nombre: "Bop It",
    descripcion: "Un cacharro de plástico que te grita órdenes absurdas ('¡Gíralo!', '¡Tíralo!') y tú obedeces como un robot sin motivo aparente.",
    categoria: "Juguetes",
    emoji: "🎮",
    año: 1996,
    precioAprox: "20 $",
    ventas: "Más de 90 millones de unidades",
    chorrada: 3,
    porQueTriunfo: "Es puro absurdo gamificado: obedecer órdenes sin sentido resulta, sorprendentemente, muy adictivo."
  },
  {
    id: "sea-monkeys",
    nombre: "Sea-Monkeys",
    descripcion: "Anunciados como una civilización submarina de simpáticos 'monos marinos'. En realidad son camarones de salmuera deshidratados.",
    categoria: "Mascotas",
    emoji: "🦐",
    año: 1960,
    precioAprox: "8 $",
    ventas: "Decenas de millones de kits vendidos",
    chorrada: 5,
    porQueTriunfo: "El engaño publicitario (dibujos de familia feliz vs. camaroncitos reales) generó fascinación mundial."
  },
  {
    id: "crocs",
    nombre: "Crocs",
    descripcion: "Zuecos de goma con agujeritos, considerados durante años el calzado más feo del planeta. Hoy tienen ediciones de lujo.",
    categoria: "Moda",
    emoji: "👞",
    año: 2002,
    precioAprox: "50 $",
    ventas: "Más de 800 millones de pares vendidos",
    chorrada: 3,
    porQueTriunfo: "Abrazó su propia fealdad, se convirtió en icono 'feo-cool' y coleccionable con los Jibbitz."
  },
  {
    id: "silly-string",
    nombre: "Silly String",
    descripcion: "Un espray que dispara una serpentina de espuma de colores para llenar de churretes a tus amigos en fiestas.",
    categoria: "Juguetes",
    emoji: "🎉",
    año: 1972,
    precioAprox: "3 $",
    ventas: "Producto de fiesta imprescindible desde hace 50 años",
    chorrada: 3,
    porQueTriunfo: "No aporta nada útil, pero el caos divertido que provoca lo hace insustituible en cumpleaños."
  },
  {
    id: "beanie-babies",
    nombre: "Beanie Babies",
    descripcion: "Peluches pequeños rellenos de bolitas de plástico, vendidos como objeto de coleccionismo e inversión.",
    categoria: "Juguetes",
    emoji: "🧸",
    año: 1993,
    precioAprox: "5 $",
    ventas: "Más de 6.000 millones de dólares en su pico",
    chorrada: 4,
    porQueTriunfo: "La escasez artificial y el rumor de que 'valdrían una fortuna' desató una fiebre especuladora real."
  },
  {
    id: "clapper",
    nombre: "The Clapper",
    descripcion: "Un dispositivo que enciende y apaga la luz con solo dar palmadas. Porque levantarse a pulsar un interruptor es demasiado esfuerzo.",
    categoria: "Hogar",
    emoji: "👏",
    año: 1984,
    precioAprox: "20 $",
    ventas: "Más de 15 millones de unidades",
    chorrada: 4,
    porQueTriunfo: "Su anuncio de infomercial ('¡Clap on! ¡Clap off!') es tan icónico que sigue siendo meme hoy en día."
  },
  {
    id: "tamagotchi",
    nombre: "Tamagotchi",
    descripcion: "Una mascota virtual dentro de un huevo de plástico que hay que alimentar, limpiar y querer... o se muere de verdad (en pantalla).",
    categoria: "Juguetes",
    emoji: "🐣",
    año: 1996,
    precioAprox: "18 $",
    ventas: "Más de 91 millones de unidades",
    chorrada: 3,
    porQueTriunfo: "Convirtió el cuidado de una mascota inexistente en una obligación emocional real y adictiva."
  },
  {
    id: "calcetines-sandalia",
    nombre: "Calcetín-sandalia (Sandal Socks)",
    descripcion: "Un híbrido que fusiona el 'crimen de moda' de llevar calcetines con sandalias en una sola prenda, oficialmente y sin remedio.",
    categoria: "Moda",
    emoji: "🧦",
    año: 2017,
    precioAprox: "18 $",
    ventas: "Viral en redes, ediciones agotadas",
    chorrada: 5,
    porQueTriunfo: "Se rió de un meme de moda ('calcetines con sandalias') y lo convirtió literalmente en el producto."
  }
];
